Web/Controllers/Authentication/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using MyConcert.Models;
using Puppy.Utils;
using Puppy.Model;
using Puppy.Model.Output;
using Newtonsoft.Json;
using System.Net.Http;

namespace MyConcert.Controllers
{
    public class AuthenticationController : Controller
    {
       
        public IActionResult AuthenReply()
        {
            
            return View();
        }

        public IActionResult LogIn()
        {
            return View();
        }

        public async Task<IActionResult> LogOn(string fbId,string fbName)
        {
            Response.Cookies.Append("fbLogIn", fbId);
            Response.Cookies.Append("fbName", fbName);
            // log in with JWT
            UserModel model = new UserModel {
                UserName = fbId,
                Password ="test"
            };
            
            RestApi api = new RestApi ("https://localhost:5003/api/user/authenticate");
            var json = JsonConvert.SerializeObject(model); 
            string token = await api.GetOneAsync(HttpMethod.Post,json );
            Response.Cookies.Append("token", token);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult LogOut()
        {
            Response.Cookies.Delete("fbLogIn");
            Response.Cookies.Delete ("fbName");
            Response.Cookies.Delete ("token");
    
            return RedirectToAction("Index", "Home");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyConcert.Models;
using Puppy.Utils;
using Puppy.Model.Output;
using MyConcert.Utils;
using Newtonsoft.Json;

namespace MyConcert.Controllers
{
    public class CustomerController : Controller
    {
        public async Task<IActionResult> MyTicket( )
        {
            string bookedBy = HttpContext.Request.Cookies["fbLogIn"].ToString();
            RestApi api = new RestApi("https://localhost:5003/api/concertSeats/TicketByOwner?ownerId="+bookedBy);
            api.SetHeader("Authorization", Cookies.GetToken(Request));
            var data = await api.GetAsync("");
            var responseBody = await data.Content.ReadAsStringAsync();
            Result result = JsonConvert.DeserializeObject<Result>(responseBody);
            List<ConcertSeatModel> list = JsonConvert.DeserializeObject<List<ConcertSeatModel>>(result.Data);
            return View(list);
        }

        public IActionResult MyProfile()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Views/Shared/Unauthorize.cshtml
@{
    ViewData["Title"] = "Unauthorize";
}

<h1 class="text-danger">Unauthorize.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

<h3>Development Mode</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My Concert</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
 
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Concert</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                   
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Concert" asp-action="Index">Concert List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="MyTicket">My Ticket</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="MyProfile">My Profile</a>
                        </li>
                    </ul>
         
                </div>
                    <ul class="nav navbar-nav navbar-right flex-grow-1">
                        <li class="nav-item"><label class="nav-link text-dark" id="user"></label></li>
                        <li class="nav-item"><a id="btnLogIn" class="nav-link" asp-controller="Authentication" asp-action="LogIn"> Login</a></li>
                        <li class="nav-item" ><a id="btnLogOut" class="nav-link" asp-controller="Authentication" asp-action="LogOut"> Logout</a></li>
                    </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2562 - My Concert - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
      
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for(var i = 0; i <ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
            c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
            }
        }
        return "";
        }

        $('#btnLogIn').show();
        $('#btnLogOut').hide();
        var token = getCookie("token");
        // console.log('token', token);
        token = JSON.parse(token);
        if (token) {
            $('#user').text(token.firstName + ' ' + token.lastName);
            $('#btnLogIn').hide();
            $('#btnLogOut').show();
        }
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>